# Generated by Django 5.0.8 on 2024-09-23 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsableVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VentasRealizadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('precio_unidad', models.IntegerField()),
                ('cantidad_vendida', models.IntegerField()),
                ('total_venta', models.IntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('responsable_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.responsableventa')),
            ],
        ),
    ]
